---
- name: Install packages
  hosts: "{{ target_group }}"
  become: yes
  tasks:
    - name: Install specified packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
