---
- name: Ping a specific group of hosts
  hosts: "{{ target_group }}"  # Variable pour définir le groupe d'hôtes
  gather_facts: no

  tasks:
    - name: Ping all hosts in the selected group
      ansible.builtin.ping:
