---
- name: Ping an IP address
  hosts: localhost
  gather_facts: no
  vars:
    ip_address: "{{ target_ip }}"  # La variable ip_address est définie en utilisant le paramètre target_ip

  tasks:
    - name: Ping the specified IP address
      ansible.builtin.ping:
        data: "Hello"
      delegate_to: "{{ ip_address }}"
      ignore_errors: yes

    - name: Check if the ping was successful
      debug:
        msg: "Ping to {{ ip_address }} was successful."
      when: ping_result is succeeded
