---
- name: Ping a collection of IP addresses or hosts
  hosts: localhost
  gather_facts: no
  vars:
    targets: "{{ inventory_group }}"  # Variable pour la collection d'IP ou d'hôtes

  tasks:
    - name: Ping each target in the collection
      ansible.builtin.ping:
        data: "Hello"
      delegate_to: "{{ item }}"
      ignore_errors: yes
      loop: "{{ targets }}"

    - name: Check if the ping was successful
      debug:
        msg: "Ping to {{ item }} was successful."
      when: ping_result is succeeded
      loop: "{{ targets }}"
